spring:
  application:
    name: grassland-shepherd
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 30000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy:  org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL57Dialect
    database: mysql
    open-in-view: true
  thymeleaf:
    mode: HTML
    cache: false

logging:
  level:
    root: info
    org.springframework.boot: info
    com.orkva.framework.grassland: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

management:
  endpoint:
    health:
      show-details: when_authorized
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: ["*"]
